language: csharp
mono: none
dist: xenial
dotnet: 6.0
addons:
  sonarcloud:
    organization: "kamilbaczek"
    token: ${SONAR_TOKEN}

install:
  - dotnet restore
  - dotnet new tool-manifest && dotnet tool install --global dotnet-reportgenerator-globaltool && dotnet tool install --global dotnet-sonarscanner
before_script:
  - export PATH="$PATH:$HOME/.dotnet/tools"
script:
  - dotnet sonarscanner begin /o:"kamilbaczek" /d:sonar.login="$SONAR_TOKEN" /v:"${TRAVIS_BUILD_NUMBER}" /d:sonar.cs.opencover.reportsPaths="**\TestResults\*\*.xml" /d:sonar.exclusions=**/*.html /k:"kamilbaczek_Estimation-Tool"
  - dotnet build
  - dotnet test -v=normal --collect:"XPlat Code Coverage" -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=opencover
  - dotnet sonarscanner end /d:sonar.login="$SONAR_TOKEN"
deploy:
  provider: heroku
  api_key: $Heroku__App__Key
  app: estimation-tool-kb
  on:
    branch: develop
notifications:
  slack: estimationtool:$Slack__Key
git:
  depth: false