language: csharp
mono: none
dist: xenial
dotnet: 5.0
install:
  - dotnet restore
script:
  - dotnet build
  - dotnet test -v=normal
notifications:
  slack: estimationtool:bOTvxHaF5GBvP2e6Q2gErCqr
deploy:
  provider: heroku
  api_key: f4e9c6a2-7620-4041-b6bb-aa0dffd1b602
  app: estimation-tool-kb
  on:
    branch: develop
