language: csharp
mono: none
dist: trusty
before_install: sudo snap alias dotnet-sdk.dotnet dotnet
jobs:
  include:
    - stage: build
      name: "Build .Net 6"
    - script: dotnet restore
    - script: dotnet build
    - stage: test
      name: "Unit Tests"
      script: dotnet test -v=normal
    - stage: deploy
      name: "Deploy to Heroku"
      deploy:
        provider: heroku
        api_key: $Heroku__App__Key
        app: estimation-tool-kb
        on:
          branch: develop
      notifications:
        slack: estimationtool:$Slack__Key