language: csharp
mono: none
dist: xenial
dotnet: 6.0
addons:
  sonarcloud:
    organization: "kamilbaczek"
    token: ${SONAR_TOKEN}

install:
  - dotnet restore
script:
  - dotnet tool install -g dotnet-reportgenerator-globaltool
  - dotnet build
  - dotnet test -v=normal /p:CollectCoverage=true /p:CoverletOutput=${TRAVIS_BUILD_DIR}\coverage\ /p:MergeWith=${TRAVIS_BUILD_DIR}\coverage\coverage.json /p:CoverletOutputFormat="json,cobertura"
  - reportgenerator "-reports:${TRAVIS_BUILD_DIR}\coverage\coverage.cobertura.xml" "-targetdir:${TRAVIS_BUILD_DIR}\coverage\Reports" -tag:${TRAVIS_BUILD_NUMBER} "-reporttypes:HTMLInline;HTMLChart;SonarQube"
  - sonar-scanner -Dsonar.projectVersion=${TRAVIS_BUILD_NUMBER}

deploy:
  provider: heroku
  api_key: $Heroku__App__Key
  app: estimation-tool-kb
  on:
    branch: develop
notifications:
  slack: estimationtool:$Slack__Key
git:
  depth: false