language: csharp
mono: none
dist: xenial
dotnet: 6.0
addons:
  sonarcloud:
    organization: "kamilbaczek"
    token: ${SONAR_TOKEN}

install:
  - dotnet restore
script:
  - dotnet new tool-manifest && dotnet tool install dotnet-reportgenerator-globaltool
  - dotnet build
  - dotnet test -v=normal --collect:"XPlat Code Coverage"
  - dotnet reportgenerator "-reports:${TRAVIS_BUILD_DIR}\**\coverage.cobertura.xml" "-targetdir:${TRAVIS_BUILD_DIR}\coverage\Reports" -tag:${TRAVIS_BUILD_NUMBER} "-reporttypes:HTMLInline;HTMLChart;SonarQube"
  - sonar-scanner -Dsonar.projectVersion=${TRAVIS_BUILD_NUMBER} -Dsonar.coverageReportPaths=${TRAVIS_BUILD_DIR}\coverage\Reports

deploy:
  provider: heroku
  api_key: $Heroku__App__Key
  app: estimation-tool-kb
  on:
    branch: develop
notifications:
  slack: estimationtool:$Slack__Key
git:
  depth: false