language: csharp
mono: none
dist: xenial
dotnet: 6.0
addons:
  sonarcloud:
    organization: "kamilbaczek"
    token: ${SONAR_TOKEN}

install:
  - dotnet restore
script:
  - dotnet build
  - dotnet test -v=normal
  - sonar-scanner -X -Dsonar.projectVersion=${TRAVIS_BUILD_NUMBER}

deploy:
  provider: heroku
  api_key: $Heroku__App__Key
  app: estimation-tool-kb
  on:
    branch: develop
notifications:
  slack: estimationtool:$Slack__Key