version: "3"
services:
  #######################################################
  #  Postgres
  #######################################################
  postgres:
    image: clkao/postgres-plv8
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: Password12!
    ports:
      - "5432:5432"