name: Build
on:
  push:
    branches:
      - develop
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
     
    - name: Checkout 
      uses: actions/checkout@v2
      with:
        fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.x' # SDK Version to use.
    - name: Install sonarscanner-dotnet
      run: dotnet new tool-manifest && dotnet tool install --global dotnet-sonarscanner
    - name: Get coverage
      run: 
    - name: Sonarscanner for dotnet
      run: |
           dotnet sonarscanner begin /o:"kamilbaczek" /d:sonar.login="$SONAR_TOKEN" /d:sonar.cs.opencover.reportsPaths="**/TestResults/*/*.xml" /d:sonar.exclusions=**/*.html /k:"kamilbaczek_Estimation-Tool"
           dotnet build
           dotnet test Src/Modules/Inquiries/Tests/Divstack.Company.Estimation.Tool.Inquiries.Domain.Tests -v=normal --collect:"XPlat Code Coverage" -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=opencover
           dotnet sonarscanner end /d:sonar.login="$SONAR_TOKEN"
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}