name: CI
on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Valuations Domain Tests
        uses: zyborg/dotnet-tests-report@v1
        with:
          project_path: Src/Modules/Valuations/Divstack.Company.Estimation.Tool.Valuations.Domain.Tests/Divstack.Company.Estimation.Tool.Valuations.Domain.Tests.csproj
          report_name: valuations_domain_project_tests
          report_title: Valuations Domain Tests
          github_token: ${{ secrets.GITHUB_TOKEN }}
